### ISSUE TITLE
Generation of localized Strings fail

### ISSUE THREAD

**Issue by pc-coholic** [pc-coholic/pretix-googlepaypasses#3]
Hi again, I've gotten access to the API and have generated my Issuer ID and Service-Account JSON file and put them in the global settings. Now I get these errors in the pretix.log file instead of a JSON formatted error message

```
ERROR 2018-11-01 20:46:53,300 django.request log Internal Server Error: /LordBonzi/rulzc/order/CJDCT/j0amg4ef0an75qwp/download/27/googlepaypasses/generate
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/utils.py", line 114, in wrap
    response = func(request=request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/utils.py", line 114, in wrap
    response = func(request=request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/views/robots.py", line 7, in dispatch
    resp = super().dispatch(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/views.py", line 35, in get
    JWT = WalletobjectOutput.getWalletObjectJWT(self.order, kwargs['position'])
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/googlepaypasses.py", line 119, in getWalletObjectJWT
    eventTicketClass = WalletobjectOutput.getOrgenerateEventTicketClass(order.event, authedSession)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/googlepaypasses.py", line 181, in getOrgenerateEventTicketClass
    return WalletobjectOutput.generateEventTicketClass(event, authedSession)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/googlepaypasses.py", line 261, in generateEventTicketClass
    event.name,
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/eventTicketClass.py", line 95, in heroImage
    self._eventTicketClass['heroImage'] = utils.image(uri, description, localizedDescriptions, self._defaultLang)
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/utils.py", line 74, in image
    'sourceUri': utils.localizedUri(uri, description, stringsDict)
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/utils.py", line 55, in localizedUri
    'localizedDescription': utils.localizedString(stringsDict, default),
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/utils.py", line 21, in localizedString
    defaultLang = next(iter(stringsDict))
StopIteration
ERROR 2018-11-01 20:46:53,300 django.request log Internal Server Error: /LordBonzi/rulzc/order/CJDCT/j0amg4ef0an75qwp/download/27/googlepaypasses/generate
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/utils.py", line 114, in wrap
    response = func(request=request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/utils.py", line 114, in wrap
    response = func(request=request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix/presale/views/robots.py", line 7, in dispatch
    resp = super().dispatch(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/views.py", line 35, in get
    JWT = WalletobjectOutput.getWalletObjectJWT(self.order, kwargs['position'])
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/googlepaypasses.py", line 119, in getWalletObjectJWT
    eventTicketClass = WalletobjectOutput.getOrgenerateEventTicketClass(order.event, authedSession)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/googlepaypasses.py", line 181, in getOrgenerateEventTicketClass
    return WalletobjectOutput.generateEventTicketClass(event, authedSession)
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_googlepaypasses/googlepaypasses.py", line 261, in generateEventTicketClass
    event.name,
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/eventTicketClass.py", line 95, in heroImage
    self._eventTicketClass['heroImage'] = utils.image(uri, description, localizedDescriptions, self._defaultLang)
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/utils.py", line 74, in image
    'sourceUri': utils.localizedUri(uri, description, stringsDict)
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/utils.py", line 55, in localizedUri
    'localizedDescription': utils.localizedString(stringsDict, default),
  File "/var/pretix/venv/lib/python3.6/site-packages/walletobjects/utils.py", line 21, in localizedString
    defaultLang = next(iter(stringsDict))
StopIteration
```

Thanks again for all your help.

_Originally posted by @LordBonzi in https://github.com/pc-coholic/pretix-googlepaypasses/issues/1#issuecomment-435182309_

**Comment by pc-coholic** [comment]
Issue with walletobjects
